# This is a config for E2B sandbox template.
# You can use template ID (yphugth3ra8do2134l7v) or template name (vibe-nextjs-jovi) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-jovi") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-jovi") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-jovi')

team_id = "d36520d1-0616-4a53-985e-9dee7b139875"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-jovi"
template_id = "yphugth3ra8do2134l7v"
